### ISSUE TITLE
PNI label

### ISSUE THREAD

**Issue by player1321** [Paip-2020/PAIP2021#1]
In the provided metric.py, the PNI_LABEL is 2.
But on the [evaluation](https://paip2021.grand-challenge.org/Evaluation/) page, the PNI_LABEL is 1:
![image](https://user-images.githubusercontent.com/38416786/122634616-b9fdcf80-d111-11eb-9999-467ce5189ec6.png)
So what should it be in the submission tif file?

**Comment by sungdukcho2** [comment]
PNI_LABEL value is used for the ground truth label and not used for submitted tif file.
You can check that the provided xml2mask.py code labels PNI pixels as 2.
Inside metric.py code, we filter out labels other than PNI using PNI_LABEL.

The submission tif file should have values of either 0 or 1.

**Comment by player1321** [comment]
Got it, thanks!
